### ISSUE TITLE
TypeError: can only join an iterable

### ISSUE THREAD

**Issue by maivierzhent** [LowriWilliams/Aspect_Sentiment_Analysis#3]
When running the count vectorizer, I am getting the following error message. Could you please help? Thank you!

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-48-03da873b04e7> in <module>
      7 
      8 for index, row in df.iterrows():
----> 9     vectors.append(", ".join(row[6]))
     10 
     11 vectorised = vectorizer.fit_transform(vectors)

TypeError: can only join an iterable

**Comment by LowriWilliams** [comment]
Hello!

So I'm not sure what you're inputting to the vectors list. 

But the row[6] refers to the 'lemmatise' column in the dataframe in the notebook. So it's worth checking whether you have a dataframe with 5 columns and if not, amending row[6] to whichever column you want in your dataframe.

**Comment by maivierzhent** [comment]
Thank you!
