### ISSUE TITLE
Bug TypeError: can only concatenate str (not "int") to str

### ISSUE THREAD

**Issue by tronglocfs** [LowriWilliams/Aspect_Sentiment_Analysis#4]
` tmp_1['topic'] = tmp_1['topic'] + 1`
When I run this line code, I receive bug: 
![image](https://user-images.githubusercontent.com/85149198/132502551-26512221-4013-443e-b2fb-375ba09772a7.png)
Please help me! Thank you very much!

**Comment by LowriWilliams** [comment]
You need to make sure your tmp_1['topic'] column is an integer. At the moment, it is a string and so you can't + 1 to a string.

Try this:

tmp_1['topic'] = tmp_1['topic'].astype(int)
tmp_1['topic'] = tmp_1['topic'] + 1

**Comment by tronglocfs** [comment]
@LowriWilliams tmp_1['topic'] is an object, so I don't astype(int) with it. I try printing tmp_1['topic'] and my result:
![image](https://user-images.githubusercontent.com/85149198/132704680-69a189e5-982f-4ce6-8655-84ab32124510.png)

**Comment by LowriWilliams** [comment]
@tronglocfs you don't need the tmp_1['topic'] + 1 line. It's just so that you don't have a topic 0. Try commenting it out.
